-- Create table for the system users.
CREATE TABLE system_users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username VARCHAR(100) NOT NULL,
    full_name VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL,
    phone_number VARCHAR(20) NOT NULL,
    role VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,

    -- ADD CONSTRAINTS
    CONSTRAINT pk_system_users PRIMARY KEY (id),
    CONSTRAINT uq_system_users_username UNIQUE (username),
    CONSTRAINT chk_system_users_username CHECK (username <> ''),
    CONSTRAINT chk_system_users_full_name CHECK (full_name <> ''),
    CONSTRAINT chk_system_users_email CHECK (email <> ''),
    CONSTRAINT chk_system_users_role CHECK (role IN ('ADMIN', 'STAFF', 'ENGINEER', 'ANALYST'))
);

-- Add samples to table - generated by ChatGPT.
INSERT INTO system_users (username, full_name, email, phone_number, role, active, created_at)
VALUES
    ('allen', 'Allen Hart', 'allen.hart@neonark.internal', '555-0101', 'ADMIN', TRUE, NOW()),
    ('sarah', 'Sarah Vale', 'sarah.vale@neonark.internal', '555-0102', 'STAFF', TRUE, NOW()),
    ('ron', 'Ron Calder', 'ron.calder@neonark.internal', '555-0103', 'ENGINEER', TRUE, NOW()),
    ('allison', 'Allison Reed', 'allison.reed@neonark.internal', '555-0104', 'ANALYST', TRUE, NOW());