-- Create observations table / use previously submitted project 3
CREATE TABLE observations (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, -- PK for each observation
                              creature_id BIGINT NOT NULL,
                              observer_name VARCHAR(100) NOT NULL,
                              note_text VARCHAR(300) NOT NULL,
                              observed_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    -- ADD CONSTRAINTS
                              CONSTRAINT pk_observations PRIMARY KEY (id), -- primary key assignment
                              CONSTRAINT fk_observations_creatures FOREIGN KEY (creature_id) REFERENCES creatures(id), -- Link id for creature reference
                              CONSTRAINT chk_observer_name CHECK ( observer_name <> '' ), -- ensure name isn't empty
                              CONSTRAINT chk_observer_note CHECK ( note_text <> '' ) -- ensure note is not blank
);

-- Add information to table using project 3 generated info - ChatGPT generated these.
INSERT INTO observations(
    creature_id,
    observer_name,
    note_text,
    observed_at
)
VALUES
    (
        (SELECT id FROM creatures WHERE name = 'Nyx'),
        'Allen',
        'Avoids bright light and keeps to shaded corners.',
        '2026-04-01 08:15:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Drakar'),
        'Sarah',
        'Burrows rapidly when disturbed.',
        '2026-04-01 09:40:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Glacia'),
        'Ron',
        'Remained calm during feeding cycle.',
        '2026-04-01 10:20:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Boglin'),
        'Allison',
        'Highly territorial near the habitat entrance.',
        '2026-04-01 11:00:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Pyron'),
        'Allen',
        'Emits strong heat waves when approached.',
        '2026-04-01 11:35:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Aeris'),
        'Sarah',
        'Observed gliding between upper ledges.',
        '2026-04-01 12:10:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Nautilux'),
        'Ron',
        'Minimal movement, bioluminescence stable.',
        '2026-04-01 13:00:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Virex'),
        'Allen',
        'Camouflage response triggered by noise.',
        '2026-04-01 13:20:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Echoid'),
        'Allison',
        'Responded to sound pulses from the west chamber.',
        '2026-04-01 14:10:00'
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Solara'),
        'Sarah',
        'Displayed short sprint bursts across the enclosure.',
        '2026-04-01 15:00:00'
    );

-- Create a way to fill in blank for time observed_at using trigger.
CREATE OR REPLACE FUNCTION set_observed_at_if_null()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.observed_at IS NULL THEN
    NEW.observed_at := CURRENT_TIMESTAMP; -- Applies timestamp from system.
END IF;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;
-- Create the trigger to be used for inserts that have no timestamp for observed_at
CREATE TRIGGER set_observed_at
    BEFORE INSERT ON observations
    FOR EACH ROW
    EXECUTE FUNCTION set_observed_at_if_null();