-- Create a feeding table that has schedules for when to feed creatures.
CREATE TABLE feeding_schedules(
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                creature_id BIGINT NOT NULL,
                                feeding_time TIME NOT NULL,
                                food_type VARCHAR(100) NOT NULL,
                                feeding_instructions TEXT,
                                active BOOLEAN NOT NULL DEFAULT TRUE,

                                -- ADD CONSTRAINTS
                                CONSTRAINT pk_feeding_schedules PRIMARY KEY (id), -- SET PK
                                CONSTRAINT fk_feeding_schedules_creatures
                                    FOREIGN KEY (creature_id) REFERENCES creatures(id), -- SET FK FOR ID
                                CONSTRAINT chk_feeding_food_type_not_blank
                                    CHECK (food_type <> '') -- ensure food type is not blank
);

-- Adds sample feeding schedules - generated by ChatGPT
INSERT INTO feeding_schedules (creature_id, feeding_time, food_type, feeding_instructions, active)
VALUES
    (
        (SELECT id FROM creatures WHERE name = 'Nyx'),
        '08:00',
        'Shadow moss',
        'Feed under dim light only.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Drakar'),
        '12:00',
        'Crimson root',
        'Use reinforced feeding tools. Keep distance.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Glacia'),
        '08:00',
        'Frost minnows',
        'Keep food frozen until feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Boglin'),
        '18:30',
        'Swamp beetles',
        'Approach slowly. Territorial behavior expected.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Pyron'),
        '12:00',
        'Ember fruit',
        'Use heat-resistant gloves.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Aeris'),
        '09:30',
        'Sky grain',
        'Place food on elevated platform.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Nautilux'),
        '20:00',
        'Deep-sea kelp',
        'Deliver food through aquatic hatch.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Virex'),
        '14:00',
        'Jungle fowl',
        'Use motion-controlled feeding drawer.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Echoid'),
        '07:30',
        'Cave nectar',
        'Avoid loud noises during feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Solara'),
        '10:00',
        'Plains grass mix',
        'Standard feeding protocol.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Thornix'),
        '08:00',
        'Vine pods',
        'Wear arm protection.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Scorch'),
        '16:00',
        'Charred bone meal',
        'Do not hand-feed.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Fangor'),
        '11:00',
        'Mountain hare',
        'Use upper feeding chute.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Krakenix'),
        '20:00',
        'Brine squid',
        'Expect ink cloud response.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Lurker'),
        '18:30',
        'Marsh fish',
        'Verify location before opening feeding port.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Shivra'),
        '08:00',
        'Frozen spores',
        'Use thermal scanner before feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Razor'),
        '12:00',
        'Desert rodents',
        'Fast strike behavior expected.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Bramble'),
        '10:00',
        'Berry clusters',
        'Low-risk feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Venox'),
        '14:00',
        'Toxic grubs',
        'Use venom-safe tools.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Stoneback'),
        '06:00',
        'Mineral blocks',
        'May remain dormant during feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Glint'),
        '07:30',
        'Crystal moths',
        'Dim lights before feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Inferno'),
        '16:00',
        'Molten core pellets',
        'Extreme heat protocol required.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Tidecaller'),
        '20:00',
        'Saltwater algae',
        'Feed during calm water cycle.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Dustling'),
        '09:30',
        'Dune seeds',
        'Avoid strong airflow during feeding.',
        TRUE
    ),
    (
        (SELECT id FROM creatures WHERE name = 'Meadowlark'),
        '10:00',
        'Field greens',
        'Docile feeding protocol.',
        TRUE
);