-- =========================
-- HABITATS (10) - Generated by ChatGPT
-- =========================

INSERT INTO habitats (biome, location, min_temp_c, max_temp_c, created_at) VALUES
('FOREST', 'Sector A — Moss Caverns', 8, 18, NOW()),
('DESERT', 'Sector B — Crimson Dunes', 30, 50, NOW()),
('ARCTIC', 'Sector C — Frost Hollow', -30, -5, NOW()),
('SWAMP', 'Sector D — Mire Basin', 15, 28, NOW()),
('MOUNTAIN', 'Sector E — Obsidian Peaks', -5, 10, NOW()),
('OCEAN', 'Sector F — Abyssal Shelf', 2, 12, NOW()),
('JUNGLE', 'Sector G — Verdant Wilds', 22, 35, NOW()),
('CAVE', 'Sector H — Echo Tunnels', 5, 14, NOW()),
('VOLCANIC', 'Sector I — Ember Rift', 40, 80, NOW()),
('PLAINS', 'Sector J — Golden Expanse', 10, 25, NOW());


-- =========================
-- CREATURES (25) - Generated by ChatGPT
-- =========================

INSERT INTO creatures (name, species, danger_level, condition, notes, habitat_id, created_at) VALUES
('Nyx', 'Void Fox', 'HIGH', 'QUARANTINED', 'Avoid bright light',
(SELECT id FROM habitats WHERE location = 'Sector A — Moss Caverns'), NOW()),

('Drakar', 'Sand Wyrm', 'EXTREME', 'ACTIVE', 'Burrows rapidly',
(SELECT id FROM habitats WHERE location = 'Sector B — Crimson Dunes'), NOW()),

('Glacia', 'Frost Serpent', 'HIGH', 'STABLE', 'Cold-resistant scales',
(SELECT id FROM habitats WHERE location = 'Sector C — Frost Hollow'), NOW()),

('Boglin', 'Swamp Imp', 'MEDIUM', 'ACTIVE', 'Highly territorial',
(SELECT id FROM habitats WHERE location = 'Sector D — Mire Basin'), NOW()),

('Pyron', 'Lava Drake', 'EXTREME', 'AGGRESSIVE', 'Emits heat waves',
(SELECT id FROM habitats WHERE location = 'Sector I — Ember Rift'), NOW()),

('Aeris', 'Sky Stalker', 'HIGH', 'STABLE', 'Glides silently',
(SELECT id FROM habitats WHERE location = 'Sector E — Obsidian Peaks'), NOW()),

('Nautilux', 'Deep Sea Leviathan', 'EXTREME', 'DORMANT', 'Bioluminescent',
(SELECT id FROM habitats WHERE location = 'Sector F — Abyssal Shelf'), NOW()),

('Virex', 'Jungle Stalker', 'HIGH', 'ACTIVE', 'Camouflaged predator',
(SELECT id FROM habitats WHERE location = 'Sector G — Verdant Wilds'), NOW()),

('Echoid', 'Cave Whisperer', 'LOW', 'STABLE', 'Responds to sound',
(SELECT id FROM habitats WHERE location = 'Sector H — Echo Tunnels'), NOW()),

('Solara', 'Plains Runner', 'LOW', 'ACTIVE', 'Extremely fast',
(SELECT id FROM habitats WHERE location = 'Sector J — Golden Expanse'), NOW()),

('Thornix', 'Forest Brute', 'MEDIUM', 'STABLE', 'Covered in vines',
(SELECT id FROM habitats WHERE location = 'Sector A — Moss Caverns'), NOW()),

('Scorch', 'Fire Hound', 'HIGH', 'AGGRESSIVE', 'Leaves burn marks',
(SELECT id FROM habitats WHERE location = 'Sector I — Ember Rift'), NOW()),

('Fangor', 'Mountain Raptor', 'HIGH', 'ACTIVE', 'Sharp talons',
(SELECT id FROM habitats WHERE location = 'Sector E — Obsidian Peaks'), NOW()),

('Krakenix', 'Mini Kraken', 'EXTREME', 'AGGRESSIVE', 'Ink clouds',
(SELECT id FROM habitats WHERE location = 'Sector F — Abyssal Shelf'), NOW()),

('Lurker', 'Swamp Beast', 'MEDIUM', 'DORMANT', 'Ambush predator',
(SELECT id FROM habitats WHERE location = 'Sector D — Mire Basin'), NOW()),

('Shivra', 'Ice Phantom', 'HIGH', 'STABLE', 'Nearly invisible',
(SELECT id FROM habitats WHERE location = 'Sector C — Frost Hollow'), NOW()),

('Razor', 'Desert Hunter', 'HIGH', 'ACTIVE', 'Fast strike speed',
(SELECT id FROM habitats WHERE location = 'Sector B — Crimson Dunes'), NOW()),

('Bramble', 'Forest Sprite', 'LOW', 'STABLE', 'Harmless unless provoked',
(SELECT id FROM habitats WHERE location = 'Sector A — Moss Caverns'), NOW()),

('Venox', 'Toxic Serpent', 'HIGH', 'AGGRESSIVE', 'Venomous bite',
(SELECT id FROM habitats WHERE location = 'Sector G — Verdant Wilds'), NOW()),

('Stoneback', 'Rock Golem', 'MEDIUM', 'DORMANT', 'Extremely durable',
(SELECT id FROM habitats WHERE location = 'Sector E — Obsidian Peaks'), NOW()),

('Glint', 'Crystal Bat', 'LOW', 'ACTIVE', 'Echolocation',
(SELECT id FROM habitats WHERE location = 'Sector H — Echo Tunnels'), NOW()),

('Inferno', 'Flame Titan', 'EXTREME', 'AGGRESSIVE', 'Massive heat output',
(SELECT id FROM habitats WHERE location = 'Sector I — Ember Rift'), NOW()),

('Tidecaller', 'Wave Spirit', 'MEDIUM', 'STABLE', 'Controls water',
(SELECT id FROM habitats WHERE location = 'Sector F — Abyssal Shelf'), NOW()),

('Dustling', 'Sand Sprite', 'LOW', 'ACTIVE', 'Moves with wind',
(SELECT id FROM habitats WHERE location = 'Sector B — Crimson Dunes'), NOW()),

('Meadowlark', 'Field Beast', 'LOW', 'STABLE', 'Docile creature',
(SELECT id FROM habitats WHERE location = 'Sector J — Golden Expanse'), NOW());